---
# https://raw.githubusercontent.com/rubocop/rubocop/master/config/default.yml
AllCops:
  TargetRubyVersion: 3.2
  NewCops: disable
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

Layout/IndentationStyle:
  Enabled: true
  EnforcedStyle: spaces

Layout/IndentationWidth:
  Enabled: true
  Width: 4

Style/MethodDefParentheses:
  Enabled: true
  EnforcedStyle: require_no_parentheses_except_multiline

Style/SpecialGlobalVars:
  Enabled: false

Style/Documentation:
  Enabled: false

Lint/MissingCopEnableDirective:
  Enabled: false

Style/AndOr:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/Not:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/StringLiterals:
  Enabled: false
